
function Curse_of_Dimensionality_Playground
% ==============================================================
%          CURSE OF DIMENSIONALITY PLAYGROUND
% ==============================================================
%
% MATLAB R2016b compatible
%
% PURPOSE:
% Demonstrate visually what happens when dimensionality increases.
%
% The program demonstrates:
%
%   1D -> 2D -> 3D -> 5D -> 10D -> 20D
%
% Main idea:
%
%     In high-dimensional spaces, a small neighbourhood
%     occupies a very tiny fraction of the total space.
%
% This makes "nearest neighbours" less informative.
%
% No Statistics and Machine Learning Toolbox required.
% ==============================================================

clc;
close all;

%% =============================================================
% PARAMETERS
% =============================================================

dimensions = [1 2 3 5 10 20];

% Number of random points
N = 1000;

% Neighbourhood radius
r = 0.2;

% Generate same random data in 20 dimensions
rng(1);

data = rand(N,20);

%% =============================================================
% MAIN FIGURE
% =============================================================

fig = figure( ...
    'Name','Curse of Dimensionality Playground', ...
    'NumberTitle','off', ...
    'Color',[1 1 1], ...
    'Position',[80 60 1250 750], ...
    'MenuBar','none', ...
    'Resize','off');

%% =============================================================
% LEFT PANEL
% =============================================================

leftPanel = uipanel( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.03 0.08 0.55 0.87], ...
    'Title','Increasing Dimensionality', ...
    'FontSize',12, ...
    'FontWeight','bold');

%% =============================================================
% RIGHT PANEL
% =============================================================

rightPanel = uipanel( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.61 0.08 0.36 0.87], ...
    'Title','What happens to neighbourhoods?', ...
    'FontSize',12, ...
    'FontWeight','bold');

%% =============================================================
% DIMENSION SLIDER
% =============================================================

uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.03 0.015 0.18 0.035], ...
    'String','Dimension:', ...
    'HorizontalAlignment','left', ...
    'FontWeight','bold', ...
    'FontSize',10);

dimensionSlider = uicontrol( ...
    'Parent',fig, ...
    'Style','slider', ...
    'Min',1, ...
    'Max',6, ...
    'Value',1, ...
    'SliderStep',[1/5 1/5], ...
    'Units','normalized', ...
    'Position',[0.15 0.025 0.25 0.025], ...
    'Callback',@dimensionChanged);

dimensionText = uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.405 0.015 0.10 0.035], ...
    'String','1D', ...
    'FontWeight','bold', ...
    'FontSize',11);

%% =============================================================
% NEIGHBOUR RADIUS
% =============================================================

uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.53 0.015 0.14 0.035], ...
    'String','Neighbour radius:', ...
    'HorizontalAlignment','left', ...
    'FontWeight','bold');

radiusSlider = uicontrol( ...
    'Parent',fig, ...
    'Style','slider', ...
    'Min',0.05, ...
    'Max',0.5, ...
    'Value',r, ...
    'Units','normalized', ...
    'Position',[0.65 0.025 0.20 0.025], ...
    'Callback',@radiusChanged);

radiusText = uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.855 0.015 0.08 0.035], ...
    'String','0.20', ...
    'FontWeight','bold');

%% =============================================================
% DRAW INITIAL STATE
% =============================================================

drawDimension(1);


%% =============================================================
% DIMENSION CALLBACK
% =============================================================

function dimensionChanged(~,~)

    index = round(get(dimensionSlider,'Value'));

    set(dimensionSlider,'Value',index);

    d = dimensions(index);

    set(dimensionText, ...
        'String',[num2str(d) 'D']);

    drawDimension(d);

end


%% =============================================================
% RADIUS CALLBACK
% =============================================================

function radiusChanged(~,~)

    r = get(radiusSlider,'Value');

    set(radiusText, ...
        'String',num2str(r,'%.2f'));

    index = round(get(dimensionSlider,'Value'));

    drawDimension(dimensions(index));

end


%% =============================================================
% MAIN DRAW FUNCTION
% =============================================================

function drawDimension(d)

    %% ----------------------------------------------------------
    % CLEAR PANELS
    % ----------------------------------------------------------

    delete(allchild(leftPanel));
    delete(allchild(rightPanel));

    %% ----------------------------------------------------------
    % LEFT SIDE
    % ----------------------------------------------------------

    if d == 1

        ax1 = axes( ...
            'Parent',leftPanel, ...
            'Units','normalized', ...
            'Position',[0.12 0.25 0.78 0.55]);

        hold(ax1,'on');

        x = data(:,1);

        y = zeros(N,1);

        plot(ax1,x,y, ...
            'k.', ...
            'MarkerSize',10);

        xlim(ax1,[0 1]);
        ylim(ax1,[-0.2 0.2]);

        xlabel(ax1,'Feature 1');
        title(ax1,'1 Dimension');

        grid(ax1,'on');

        % Neighbourhood
        testPoint = 0.5;

        plot(ax1,testPoint,0, ...
            'rp', ...
            'MarkerSize',14, ...
            'MarkerFaceColor','r');

        line( ...
            [testPoint-r testPoint+r], ...
            [0 0], ...
            'Color','r', ...
            'LineWidth',5);

    elseif d == 2

        ax1 = axes( ...
            'Parent',leftPanel, ...
            'Units','normalized', ...
            'Position',[0.10 0.25 0.80 0.55]);

        scatter(ax1, ...
            data(:,1), ...
            data(:,2), ...
            10,'filled');

        xlim(ax1,[0 1]);
        ylim(ax1,[0 1]);

        xlabel(ax1,'Feature 1');
        ylabel(ax1,'Feature 2');

        title(ax1,'2 Dimensions');

        grid(ax1,'on');

        hold(ax1,'on');

        testPoint = [0.5 0.5];

        plot(ax1, ...
            testPoint(1), ...
            testPoint(2), ...
            'rp', ...
            'MarkerSize',14, ...
            'MarkerFaceColor','r');

        rectangle( ...
            'Position',[0.5-r 0.5-r 2*r 2*r], ...
            'Curvature',[1 1], ...
            'EdgeColor','r', ...
            'LineWidth',2);

    elseif d == 3

        ax1 = axes( ...
            'Parent',leftPanel, ...
            'Units','normalized', ...
            'Position',[0.08 0.20 0.84 0.65]);

        scatter3(ax1, ...
            data(:,1), ...
            data(:,2), ...
            data(:,3), ...
            12,'filled');

        xlabel(ax1,'Feature 1');
        ylabel(ax1,'Feature 2');
        zlabel(ax1,'Feature 3');

        title(ax1,'3 Dimensions');

        xlim(ax1,[0 1]);
        ylim(ax1,[0 1]);
        zlim(ax1,[0 1]);

        grid(ax1,'on');

        view(ax1,35,25);

        hold(ax1,'on');

        plot3(ax1, ...
            0.5,0.5,0.5, ...
            'rp', ...
            'MarkerSize',15, ...
            'MarkerFaceColor','r');

    else

        % ------------------------------------------------------
        % HIGH-DIMENSION REPRESENTATION
        % ------------------------------------------------------

        ax1 = axes( ...
            'Parent',leftPanel, ...
            'Units','normalized', ...
            'Position',[0.10 0.28 0.80 0.55]);

        % Show first two dimensions
        scatter(ax1, ...
            data(:,1), ...
            data(:,2), ...
            10,'filled');

        xlim(ax1,[0 1]);
        ylim(ax1,[0 1]);

        xlabel(ax1,'Feature 1');
        ylabel(ax1,'Feature 2');

        title(ax1, ...
            [num2str(d) ' Dimensions']);

        grid(ax1,'on');

        hold(ax1,'on');

        plot(ax1, ...
            0.5,0.5, ...
            'rp', ...
            'MarkerSize',15, ...
            'MarkerFaceColor','r');

        % ------------------------------------------------------
        % Dimension labels
        % ------------------------------------------------------

        text(ax1, ...
            0.05,0.92, ...
            ['Actual feature space = ' num2str(d) 'D'], ...
            'FontSize',12, ...
            'FontWeight','bold');

        text(ax1, ...
            0.05,0.84, ...
            ['Plot shows only Feature 1 vs Feature 2'], ...
            'FontSize',10);

        text(ax1, ...
            0.05,0.76, ...
            ['There are ' num2str(d) ' independent directions'], ...
            'FontSize',10);

    end


    %% =========================================================
    % RIGHT PANEL
    % =========================================================

    % Volume/fraction of neighbourhood
    %
    % For a hypersphere, exact volume gets complicated.
    % For teaching, use a hypercube neighbourhood:
    %
    % side length = 2r
    %
    % Volume = (2r)^d
    %
    % Total unit hypercube volume = 1

    fraction = (2*r)^d;

    % Number of expected random points
    expectedPoints = N*fraction;

    %% ----------------------------------------------------------
    % RIGHT SIDE TITLE
    % ----------------------------------------------------------

    uicontrol( ...
        'Parent',rightPanel, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[0.08 0.86 0.84 0.08], ...
        'String', ...
        [num2str(d) ' DIMENSIONS'], ...
        'FontSize',16, ...
        'FontWeight','bold');

    %% ----------------------------------------------------------
    % FORMULA
    % ----------------------------------------------------------

    uicontrol( ...
        'Parent',rightPanel, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[0.08 0.73 0.84 0.10], ...
        'String',{ ...
        'Neighbourhood fraction'; ...
        ''; ...
        ['(2r)^d = ' num2str(fraction,'%.6f')]}, ...
        'FontSize',12, ...
        'FontWeight','bold');

    %% ----------------------------------------------------------
    % EXPECTED POINTS
    % ----------------------------------------------------------

    uicontrol( ...
        'Parent',rightPanel, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[0.08 0.59 0.84 0.10], ...
        'String',{ ...
        'Expected training points'; ...
        ''; ...
        ['N × fraction = ' num2str(expectedPoints,'%.3f')]}, ...
        'FontSize',11);

    %% ----------------------------------------------------------
    % EXPLANATION
    % ----------------------------------------------------------

    if d <= 2

        explanation = { ...
            'Most of the space is'; ...
            'reasonably close to a'; ...
            'given point.'; ...
            ''; ...
            'Nearest neighbours'; ...
            'can be meaningful.'};

    elseif d <= 5

        explanation = { ...
            'The neighbourhood'; ...
            'occupies a much smaller'; ...
            'fraction of the space.'; ...
            ''; ...
            'Data becomes sparse.'};

    else

        explanation = { ...
            'The neighbourhood is'; ...
            'an extremely tiny'; ...
            'fraction of the space.'; ...
            ''; ...
            'Data becomes very sparse.'; ...
            ''; ...
            'Nearest neighbours may'; ...
            'no longer be very near.'};

    end

    uicontrol( ...
        'Parent',rightPanel, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[0.08 0.30 0.84 0.24], ...
        'String',explanation, ...
        'HorizontalAlignment','left', ...
        'FontSize',11);

    %% ----------------------------------------------------------
    % KEY MESSAGE
    % ----------------------------------------------------------

    if d >= 10

        message = { ...
            'KEY IDEA'; ...
            ''; ...
            'Adding dimensions creates'; ...
            'more possible directions'; ...
            'in which data can spread.'; ...
            ''; ...
            'The same neighbourhood'; ...
            'becomes exponentially'; ...
            'smaller relative to the'; ...
            'entire space.'};

    else

        message = { ...
            'KEY IDEA'; ...
            ''; ...
            'Increasing dimension'; ...
            'increases the volume'; ...
            'of the feature space.'};

    end

    uicontrol( ...
        'Parent',rightPanel, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[0.08 0.05 0.84 0.21], ...
        'String',message, ...
        'HorizontalAlignment','left', ...
        'FontSize',10, ...
        'FontWeight','bold', ...
        'BackgroundColor',[0.95 0.95 0.95]);

end

end
